services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    environment:
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_HOST=n8n.h5-games-toos.online
      - WEBHOOK_TUNNEL_URL=https://n8n.h5-games-toos.online
    expose:
      - "5678"
    volumes:
      - n8n_data:/home/node/.n8n
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n.rule=Host(`n8n.h5-games-toos.online`)
      - traefik.http.routers.n8n.entrypoints=websecure
      - traefik.http.services.n8n.loadbalancer.server.port=5678
      - traefik.docker.network=dokploy-network
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
volumes:
  n8n_data:
